/* Nzinga Admin — navegação única, ordem fixa e estados de secção. */
(function(){
'use strict';
function start(){
 if(!/admin\.html$/i.test(location.pathname))return;
 var nav=document.querySelector('.side-nav');if(!nav||document.getElementById('nz-admin-center-ready'))return;
 var marker=document.createElement('span');marker.id='nz-admin-center-ready';marker.hidden=true;document.body.appendChild(marker);
 var s=document.createElement('style');s.id='nzinga-admin-center-style';s.textContent=''+
  '.side-nav{gap:8px!important}.side-nav button{gap:11px!important;position:relative}.nz-admin-nav-icon{width:22px;height:22px;display:grid;place-items:center;flex:none}.nz-admin-nav-icon svg{width:19px;height:19px;fill:none;stroke:currentColor;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}.side-nav button.active{box-shadow:4px 4px 0 #d71920!important}.side-nav button[data-tab="overview"]{border-left:4px solid #f2c400}.side-nav button[data-tab="products"]{border-left:4px solid #d71920}.side-nav button[data-tab="orders"]{border-left:4px solid #f2c400}.side-nav button[data-tab="reviews"]{border-left:4px solid #d71920}.side-nav button[data-tab="users"]{border-left:4px solid #f2c400}.side-nav button[data-tab="team"]{border-left:4px solid #d71920}.side-nav button[data-tab="audit"]{border-left:4px solid #f2c400}.side-nav button:focus-visible{outline:3px solid #f2c400;outline-offset:2px}.admin-actions button:focus-visible,.admin-actions select:focus-visible,.nz-admin-delete:focus-visible{outline:3px solid #f2c400;outline-offset:2px}';document.head.appendChild(s);
 var icons={overview:'<svg viewBox="0 0 24 24"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>',products:'<svg viewBox="0 0 24 24"><path d="M4 8h16l-1 12H5L4 8Z"/><path d="M8 8a4 4 0 0 1 8 0"/></svg>',orders:'<svg viewBox="0 0 24 24"><path d="M6 3h12v18H6z"/><path d="M9 7h6M9 11h6M9 15h4"/></svg>',reviews:'<svg viewBox="0 0 24 24"><path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9L12 3Z"/></svg>',users:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3"/><path d="M5 20c.8-3.5 3.2-5 7-5s6.2 1.5 7 5"/></svg>',team:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><circle cx="17" cy="10" r="2.2"/><path d="M3.5 20c.7-3.5 2.5-5 5.5-5s4.8 1.5 5.5 5M14 16c2.8 0 4.6 1.2 5.2 4"/></svg>',audit:'<svg viewBox="0 0 24 24"><path d="M7 5c2.5-2 7-1.2 8.5 1.2 1.2 2 .5 3.8-1.1 5.1 2.1.8 3.6 2.6 3.6 4.7 0 3.2-3 5-6.8 5-3.1 0-5.7-1.4-6.5-3.7-.7-2 .2-3.7 2.2-4.6-1.6-.9-2.4-2.3-2.2-4 .2-1.5 1.1-2.8 2.3-3.7Z"/><path d="M9.2 8.2c1.4.7 2.7.6 4-.1M8.8 14.2c1.4-.7 3-.7 4.5.1"/></svg>'};
 var labels={overview:'Tudo',products:'Market',orders:'Pedidos',reviews:'Avaliações',users:'Utilizadores',team:'Equipa',audit:'Atividades'};
 var order=['overview','products','orders','reviews','users','team','audit'];
 function ensureButton(k){var b=nav.querySelector('button[data-tab="'+k+'"]');if(!b){b=document.createElement('button');b.type='button';b.dataset.tab=k}b.innerHTML='<span class="nz-admin-nav-icon" aria-hidden="true">'+icons[k]+'</span><span>'+labels[k]+'</span>';b.title=labels[k];b.setAttribute('aria-label',labels[k]);return b}
 function normalize(){order.forEach(function(k){nav.appendChild(ensureButton(k))})}
 function activate(tab){normalize();nav.querySelectorAll('button[data-tab]').forEach(function(b){b.classList.toggle('active',b.dataset.tab===tab)});document.querySelectorAll('.admin-panel').forEach(function(p){p.hidden=p.id!=='panel-'+tab});var stats=document.getElementById('stats');if(stats)stats.style.display=tab==='overview'?'grid':'none';var b=nav.querySelector('button[data-tab="'+tab+'"]'),title=document.querySelector('.admin-top h1');if(title)title.textContent=tab==='overview'?'Visão geral':(b?b.textContent.trim():'Visão geral');window.scrollTo({top:0,behavior:'smooth'})}
 normalize();
 nav.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('button[data-tab]');if(!b)return;e.preventDefault();activate(b.dataset.tab);if(b.dataset.tab==='overview'&&window.NzingaAdminOverview)window.NzingaAdminOverview.refresh()});
 document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('[data-admin-section]');if(!b)return;var target=nav.querySelector('button[data-tab="'+b.dataset.adminSection+'"]');if(target)target.click()});
 new MutationObserver(function(){normalize()}).observe(nav,{childList:true});
 setTimeout(function(){activate('overview')},800);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
