/* Nzinga Admin — única navegação, ícones e estados de secção. */
(function(){
'use strict';
function start(){
 if(!/admin\.html$/i.test(location.pathname))return;
 var nav=document.querySelector('.side-nav');if(!nav||document.getElementById('nz-admin-center-ready'))return;
 var marker=document.createElement('span');marker.id='nz-admin-center-ready';marker.hidden=true;document.body.appendChild(marker);
 var s=document.createElement('style');s.id='nzinga-admin-center-style';s.textContent=''+
  '.side-nav button{gap:11px!important}.nz-admin-nav-icon{width:20px;height:20px;display:grid;place-items:center;flex:none}.nz-admin-nav-icon svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}.side-nav button.active{box-shadow:4px 4px 0 #d71920!important}.side-nav button[data-tab="overview"]{border-left:4px solid #f2c400}.side-nav button[data-tab="products"] .nz-admin-nav-icon{color:#b18b00}.side-nav button[data-tab="orders"] .nz-admin-nav-icon{color:#d71920}.side-nav button[data-tab="reviews"] .nz-admin-nav-icon{color:#b18b00}.side-nav button[data-tab="users"] .nz-admin-nav-icon{color:#d71920}.side-nav button[data-tab="team"] .nz-admin-nav-icon{color:#b18b00}.side-nav button[data-tab="audit"] .nz-admin-nav-icon{color:#d71920}.admin-actions button:focus-visible,.admin-actions select:focus-visible,.nz-admin-delete:focus-visible{outline:3px solid #f2c400;outline-offset:2px}';document.head.appendChild(s);
 var icons={overview:'<svg viewBox="0 0 24 24"><path d="M4 5h6v6H4zM14 5h6v6h-6zM4 15h6v6H4zM14 15h6v6h-6z"/></svg>',products:'<svg viewBox="0 0 24 24"><path d="M4 8h16l-1 12H5L4 8Z"/><path d="M8 8a4 4 0 0 1 8 0"/></svg>',orders:'<svg viewBox="0 0 24 24"><path d="M6 4h12v16H6zM9 8h6M9 12h6M9 16h4"/></svg>',reviews:'<svg viewBox="0 0 24 24"><path d="m12 4 2.2 4.5 4.8.7-3.5 3.4.8 4.8-4.3-2.3-4.3 2.3.8-4.8L5 9.2l4.8-.7z"/></svg>',users:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="3"/><path d="M5 20c.8-3.5 3.2-5 7-5s6.2 1.5 7 5"/></svg>',team:'<svg viewBox="0 0 24 24"><circle cx="9" cy="9" r="3"/><circle cx="17" cy="10" r="2"/><path d="M3.5 20c.7-3.3 2.5-5 5.5-5s4.8 1.7 5.5 5M14 15c2.5-.2 4.2 1.2 5 4"/></svg>',audit:'<svg viewBox="0 0 24 24"><path d="m12 3 2 5 5 .6-3.8 3.2 1.2 5-4.4-2.6L7.6 17l1.2-5L5 8.6 10 8z"/></svg>'};
 var labels={overview:'Tudo',products:'Market',orders:'Pedidos',reviews:'Avaliações',users:'Utilizadores',team:'Equipa',audit:'Atividades'};
 function ensureOverview(){if(nav.querySelector('button[data-tab="overview"]'))return;var b=document.createElement('button');b.type='button';b.dataset.tab='overview';b.innerHTML='<span class="nz-admin-nav-icon" aria-hidden="true">'+icons.overview+'</span><span>Tudo</span>';nav.insertBefore(b,nav.firstChild)}
 function normalize(){ensureOverview();Object.keys(icons).forEach(function(k){var b=nav.querySelector('button[data-tab="'+k+'"]');if(b)b.innerHTML='<span class="nz-admin-nav-icon" aria-hidden="true">'+icons[k]+'</span><span>'+labels[k]+'</span>'});nav.querySelectorAll('button').forEach(function(b){b.title=b.textContent.trim();b.setAttribute('aria-label',b.textContent.trim())})}
 function activate(tab){normalize();nav.querySelectorAll('button[data-tab]').forEach(function(b){b.classList.toggle('active',b.dataset.tab===tab)});document.querySelectorAll('.admin-panel').forEach(function(p){p.hidden=p.id!=='panel-'+tab});var stats=document.getElementById('stats');if(stats)stats.style.display=tab==='overview'?'grid':'none';var b=nav.querySelector('button[data-tab="'+tab+'"]'),title=document.querySelector('.admin-top h1');if(title)title.textContent=tab==='overview'?'Visão geral':(b?b.textContent.trim():'Visão geral');window.scrollTo({top:0,behavior:'smooth'})}
 normalize();
 nav.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('button[data-tab]');if(!b)return;e.preventDefault();activate(b.dataset.tab);if(b.dataset.tab==='overview'&&window.NzingaAdminOverview)window.NzingaAdminOverview.refresh()});
 document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('[data-admin-section]');if(!b)return;var target=nav.querySelector('button[data-tab="'+b.dataset.adminSection+'"]');if(target)target.click()});
 new MutationObserver(function(){normalize()}).observe(nav,{childList:true});
 setTimeout(function(){activate('overview')},800);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();