/* Nzinga Admin — Atividade administrativa / auditoria. */
(function(){
'use strict';
function start(){
 if(!window.supabase||!window.NZINGA_SUPABASE)return;
 var sb=window.supabase.createClient(window.NZINGA_SUPABASE.url,window.NZINGA_SUPABASE.publishableKey),app=document.getElementById('app'),nav=document.querySelector('.side-nav'),content=document.querySelector('.admin-content');
 if(!app||!nav||!content)return;
 var tab=nav.querySelector('button[data-tab="audit"]');if(!tab||document.getElementById('panel-audit'))return;
 addStyle();
 var panel=document.createElement('div');panel.id='panel-audit';panel.className='admin-panel';panel.hidden=true;content.appendChild(panel);
 var page=0,limit=50,lastRows=[];
 var actionLabels={'admin.member_added':'Membro adicionado à equipa','admin.role_changed':'Função da equipa alterada','admin.member_removed':'Membro removido da equipa','market.product_created':'Produto criado','market.product_updated':'Produto atualizado','market.product_deleted':'Produto eliminado','orders.status_changed':'Estado do pedido alterado','orders.order_deleted':'Pedido eliminado','reviews.moderated':'Avaliação moderada','reviews.deleted':'Avaliação eliminada'};
 var tableLabels={admin_users:'Equipa',market_products:'Market',orders:'Pedidos',reviews:'Avaliações'};
 function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
 function labelAction(a){return actionLabels[a]||'Atividade administrativa'}
 function icon(a){if(a&&a.indexOf('market.')===0)return '▦';if(a&&a.indexOf('orders.')===0)return '◷';if(a&&a.indexOf('reviews.')===0)return '★';return '♜'}
 function localDate(v){var d=new Date(v);return isNaN(d)?'—':d.toLocaleString('pt-AO')}
 function prettyDetails(details){if(!details||typeof details!=='object')return '';var labels={title:'Título',price:'Preço',category:'Categoria',currency:'Moeda',status:'Estado',role:'Função',customer_name:'Cliente',customer_contact:'Contacto',product_name:'Produto'};var parts=[];Object.keys(details).forEach(function(k){if(details[k]===null||details[k]===undefined||details[k]==='')return;parts.push((labels[k]||k)+': '+String(details[k]))});return parts.join(' · ')}
 async function load(reset){if(reset){page=0;lastRows=[]}panel.innerHTML='<div class="panel-head"><h2>Atividades</h2><span>A carregar…</span></div>';var r=await sb.from('admin_audit_logs').select('*').order('created_at',{ascending:false}).range(page*limit,page*limit+limit-1);if(r.error){panel.innerHTML='<div class="empty">Não foi possível carregar as atividades.<br><small>'+esc(r.error.message)+'</small></div>';return}var rows=r.data||[];lastRows=page?lastRows.concat(rows):rows;var actorIds=[...new Set(rows.map(function(x){return x.actor_id}).filter(Boolean))],profiles={};if(actorIds.length){var pr=await sb.from('profiles').select('id,name,contact').in('id',actorIds);(pr.data||[]).forEach(function(x){profiles[x.id]=x})}render(lastRows,profiles)}
 function render(rows,profiles){var action=(document.getElementById('auditAction')?.value||''),table=(document.getElementById('auditTable')?.value||'');var filtered=rows.filter(function(x){return(!action||x.action===action)&&(!table||x.target_table===table)});panel.innerHTML='';var head=document.createElement('div');head.className='panel-head';head.innerHTML='<div><h2>Atividades</h2><span>Histórico administrativo, organizado por área</span></div>';panel.appendChild(head);var tools=document.createElement('div');tools.className='audit-tools';tools.innerHTML='<select id="auditAction"><option value="">Todas as ações</option>'+Object.keys(actionLabels).map(function(k){return '<option value="'+esc(k)+'">'+esc(actionLabels[k])+'</option>'}).join('')+'</select><select id="auditTable"><option value="">Todas as áreas</option>'+Object.keys(tableLabels).map(function(k){return '<option value="'+k+'">'+tableLabels[k]+'</option>'}).join('')+'</select><button id="auditRefresh" type="button">Atualizar</button>';panel.appendChild(tools);var summary=document.createElement('div');summary.className='audit-summary';summary.innerHTML='<span class="audit-pill">Hoje: '+rows.filter(function(x){return new Date(x.created_at).toDateString()===new Date().toDateString()}).length+'</span><span class="audit-pill">Carregados: '+rows.length+'</span>';panel.appendChild(summary);tools.querySelector('#auditAction').addEventListener('change',function(){render(rows,profiles)});tools.querySelector('#auditTable').addEventListener('change',function(){render(rows,profiles)});tools.querySelector('#auditRefresh').addEventListener('click',function(){load(true)});var list=document.createElement('div');list.className='audit-list';if(filtered.length){list.innerHTML=filtered.map(function(x){var p=profiles[x.actor_id]||{},actor=p.name||p.contact||'Administrador',detail=prettyDetails(x.details),fallback=x.details&&Object.keys(x.details).length&&!detail?JSON.stringify(x.details):'';return '<article class="audit-row"><div class="audit-icon">'+icon(x.action)+'</div><div><h3>'+esc(labelAction(x.action))+'</h3><p><strong>'+esc(actor)+'</strong> · '+esc(tableLabels[x.target_table]||'Outra área')+'</p>'+(detail?'<div class="audit-details">'+esc(detail)+'</div>':'')+(fallback?'<div class="audit-details">'+esc(fallback)+'</div>':'')+'</div><time class="audit-time">'+esc(localDate(x.created_at))+'</time></article>'}).join('')}else list.innerHTML='<div class="audit-empty"><strong>Nenhuma atividade encontrada</strong><br>Não existem atividades com estes filtros.</div>';panel.appendChild(list);var more=document.createElement('div');more.className='audit-more';more.innerHTML='<button type="button">Carregar mais</button>';more.querySelector('button').disabled=rows.length<limit;more.querySelector('button').addEventListener('click',function(){page++;load(false)});panel.appendChild(more)}
 tab.addEventListener('click',function(){document.querySelectorAll('.side-nav button').forEach(function(b){b.classList.toggle('active',b===tab)});document.querySelectorAll('.admin-panel').forEach(function(p){p.hidden=p!==panel});var stats=document.getElementById('stats');if(stats)stats.style.display='none';load(true)});
 function addStyle(){if(document.getElementById('nzinga-audit-style'))return;var s=document.createElement('style');s.id='nzinga-audit-style';s.textContent='.audit-tools{padding:14px 20px;border-bottom:1px solid var(--admin-line);display:grid;grid-template-columns:1fr 1fr auto;gap:8px;background:#fff9df}.audit-tools select{width:100%;padding:10px 11px;border:1px solid #c9c4bb;border-radius:10px;background:#fff;color:#111;font:inherit}.audit-tools button{border:1px solid #d6a900;border-radius:10px;background:#f2c400;color:#111;font-weight:900;padding:10px 14px;cursor:pointer}.audit-summary{display:flex;gap:8px;flex-wrap:wrap;padding:12px 20px;border-bottom:1px solid var(--admin-line)}.audit-pill{padding:7px 10px;border:1px solid #e1b800;border-radius:999px;background:#fff4bd;font-size:.74rem}.audit-list{display:grid}.audit-row{padding:17px 20px;border-bottom:1px solid var(--admin-line);display:grid;grid-template-columns:42px minmax(0,1fr) auto;gap:12px;align-items:start}.audit-icon{width:38px;height:38px;border-radius:12px;display:grid;place-items:center;font-weight:900;background:#ffe1e3;color:#d71920;border:1px solid #f0b8bc}.audit-row h3{margin:0 0 5px;font-size:.98rem;color:#d71920}.audit-row p{margin:3px 0;opacity:.62;font-size:.82rem;line-height:1.45}.audit-time{font-size:.72rem;opacity:.48;white-space:nowrap}.audit-details{margin-top:8px;padding:9px 11px;border-radius:10px;background:#f8f6f2;font-size:.78rem;word-break:break-word}.audit-empty{padding:44px 20px;text-align:center;opacity:.5}.audit-more{padding:14px 20px;text-align:center}.audit-more button{border:1px solid #d6a900;background:#fff4bd;color:#111;border-radius:10px;padding:9px 14px;cursor:pointer;font-weight:800}@media(max-width:700px){.audit-tools{grid-template-columns:1fr}.audit-row{grid-template-columns:36px minmax(0,1fr)}.audit-time{grid-column:2;white-space:normal}.audit-icon{width:34px;height:34px}}';document.head.appendChild(s)}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',function(){setTimeout(start,250)});else setTimeout(start,250);
})();
