/* Nzinga Admin — avaliação com moderação segura antes de publicar. */
(function(){
'use strict';
function start(){
 if(!window.supabase||!window.NZINGA_SUPABASE)return;
 var panel=document.getElementById('panel-reviews');if(!panel)return;
 var sb=window.supabase.createClient(window.NZINGA_SUPABASE.url,window.NZINGA_SUPABASE.publishableKey),admin=null,rows=[];
 addStyle();sb.auth.getSession().then(function(r){admin=r?.data?.session?.user||null;load()});
 function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
 function date(v){var d=new Date(v);return isNaN(d)?'—':d.toLocaleString('pt-AO')}
 function label(s){return ({pending:'Pendente',published:'Publicada',hidden:'Oculta',rejected:'Rejeitada',archived:'Arquivada'})[s]||s||'Pendente'}
 function badge(s){return '<span class="review-status review-'+esc(s)+'">'+esc(label(s))+'</span>'}
 async function load(){panel.innerHTML='<div class="panel-head"><h2>Avaliações</h2><span>A carregar…</span></div><div class="empty">A carregar avaliações…</div>';var r=await sb.from('reviews').select('*').order('created_at',{ascending:false});if(r.error){panel.innerHTML='<div class="empty"><strong>Não foi possível carregar as avaliações.</strong>'+esc(r.error.message)+'</div>';return}rows=r.data||[];render()}
 function render(){var q=(document.getElementById('reviewsSearch')?.value||'').toLowerCase().trim(),f=document.getElementById('reviewsFilter')?.value||'';var list=rows.filter(function(x){var text=[x.text,x.user_id,x.status,x.stars].join(' ').toLowerCase();return(!q||text.indexOf(q)!==-1)&&(!f||x.status===f)});panel.innerHTML='<div class="panel-head"><h2>Avaliações</h2><span>'+rows.length+' registo'+(rows.length===1?'':'s')+'</span></div><div class="reviews-tools"><input id="reviewsSearch" type="search" placeholder="Pesquisar avaliação ou utilizador…"><select id="reviewsFilter"><option value="">Todos</option><option value="pending">Pendentes</option><option value="published">Publicadas</option><option value="hidden">Ocultas</option><option value="rejected">Rejeitadas</option></select><button id="reviewsRefresh" type="button">Atualizar</button></div><div class="reviews-count">'+list.length+' avaliação'+(list.length===1?'':'ções')+' visível'+(list.length===1?'':'is')+'</div>';document.getElementById('reviewsSearch').value=q;document.getElementById('reviewsFilter').value=f;document.getElementById('reviewsSearch').oninput=render;document.getElementById('reviewsFilter').onchange=render;document.getElementById('reviewsRefresh').onclick=load;if(!list.length){var e=document.createElement('div');e.className='empty';e.innerHTML='<strong>Nenhuma avaliação encontrada</strong>';panel.appendChild(e);return}list.forEach(function(x){var card=document.createElement('article');card.className='admin-card';card.innerHTML='<span class="admin-meta">'+badge(x.status)+' · '+esc(x.stars)+' ★ · '+esc(date(x.created_at))+'</span><p class="review-text">'+esc(x.text||'Sem comentário')+'</p><small class="review-id">Utilizador: '+esc(x.user_id)+'</small><div class="admin-actions"><button type="button" class="approve" data-action="publish">Publicar</button><button type="button" data-action="hide">Ocultar</button><button type="button" class="danger" data-action="reject">Rejeitar</button><button type="button" class="danger" data-action="delete">Eliminar</button><button type="button" data-review-details>Ver detalhes</button></div>';var pub=card.querySelector('[data-action="publish"]'),hide=card.querySelector('[data-action="hide"]'),rej=card.querySelector('[data-action="reject"]'),del=card.querySelector('[data-action="delete"]');pub.style.display=x.status==='published'?'none':'';hide.style.display=x.status==='hidden'?'none':'';pub.onclick=function(){moderate(x.id,'published')};hide.onclick=function(){moderate(x.id,'hidden')};rej.onclick=function(){moderate(x.id,'rejected')};del.onclick=function(){removeReview(x.id)};card.querySelector('[data-review-details]').onclick=function(){details(card,x)};panel.appendChild(card)})}
 async function moderate(id,status){if(!admin)return;var r=await sb.from('reviews').update({status:status,moderated_at:new Date().toISOString(),moderated_by:admin.id}).eq('id',id);if(r.error){alert('Não foi possível moderar: '+r.error.message);return}await load()}
 async function removeReview(id){if(!admin||!confirm('Eliminar esta avaliação permanentemente?'))return;var r=await sb.from('reviews').delete().eq('id',id);if(r.error){alert('Não foi possível eliminar: '+r.error.message);return}await load()}
 function details(card,x){var old=card.querySelector('.review-details');if(old){old.remove();return}var d=document.createElement('div');d.className='review-details';d.innerHTML='<dl><dt>ID</dt><dd>'+esc(x.id)+'</dd><dt>Utilizador</dt><dd>'+esc(x.user_id)+'</dd><dt>Classificação</dt><dd>'+esc(x.stars)+' / 5</dd><dt>Estado</dt><dd>'+esc(label(x.status))+'</dd><dt>Texto</dt><dd>'+esc(x.text||'—')+'</dd><dt>Criada</dt><dd>'+esc(date(x.created_at))+'</dd><dt>Moderada</dt><dd>'+esc(date(x.moderated_at))+'</dd></dl>';card.appendChild(d)}
 function addStyle(){if(document.getElementById('nzinga-reviews-style'))return;var s=document.createElement('style');s.id='nzinga-reviews-style';s.textContent='.reviews-tools{padding:14px 20px;border-bottom:1px solid var(--admin-line);display:grid;grid-template-columns:minmax(180px,1fr) 190px auto;gap:8px;background:var(--admin-soft)}.reviews-tools input,.reviews-tools select{width:100%;box-sizing:border-box;padding:10px 11px;border:1px solid var(--admin-line);border-radius:10px;background:#fff;color:#171717;font:inherit}.reviews-tools button{border:1px solid #d6a900;border-radius:10px;background:#f2c400;color:#171717;font-weight:800;padding:10px 14px;cursor:pointer}.reviews-count{font-size:.76rem;opacity:.55;padding:0 20px 12px}.review-text{font-size:1rem;line-height:1.6}.review-id{opacity:.4;word-break:break-all}.review-details{margin-top:12px;padding:14px;border:1px solid var(--admin-line);border-radius:14px;background:var(--admin-soft)}.review-details dl{margin:0;display:grid;grid-template-columns:150px 1fr;gap:7px 12px;font-size:.84rem}.review-details dt{opacity:.5}.review-details dd{margin:0;word-break:break-word}.review-status{display:inline-block;padding:3px 7px;border-radius:999px;border:1px solid #d6a900;text-transform:none;opacity:1}.review-pending{background:#f2c400;color:#171717}.review-published{background:#171717;color:#fff;border-color:#171717}.review-hidden{background:#eee;color:#555;border-color:#bbb}.review-rejected{background:#d71920;color:#fff;border-color:#d71920}@media(max-width:650px){.reviews-tools{grid-template-columns:1fr}.review-details dl{grid-template-columns:1fr}}';document.head.appendChild(s)}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();