/* Nzinga Admin — gestão de utilizadores e perfis. */
(function(){
'use strict';
function start(){
 if(!window.supabase||!window.NZINGA_SUPABASE)return;
 var panel=document.getElementById('panel-users');if(!panel)return;
 var sb=window.supabase.createClient(window.NZINGA_SUPABASE.url,window.NZINGA_SUPABASE.publishableKey),currentUser=null,profiles=[],admins=[];
 addStyle(); sb.auth.getSession().then(function(r){currentUser=r&&r.data&&r.data.session?r.data.session.user:null;load()});
 function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]})}
 function date(v){if(!v)return '—';var d=new Date(v);return isNaN(d)?'—':d.toLocaleString('pt-AO')}
 function initials(name,email){var s=(name||email||'Nz').trim(),p=s.split(/\s+/).filter(Boolean);return ((p[0]||'N')[0]+(p.length>1?p[p.length-1][0]:'')).toUpperCase().slice(0,2)}
 function avatar(path,name,email){if(!path)return '<div class="user-avatar user-avatar-fallback">'+esc(initials(name,email))+'</div>';var url=sb.storage.from('profile-photos').getPublicUrl(path).data.publicUrl;return '<img class="user-avatar" src="'+esc(url)+'" alt="" loading="lazy">'}
 function header(){return '<div class="panel-head"><h2>Utilizadores</h2><span id="usersTotal">'+profiles.length+' registo'+(profiles.length===1?'':'s')+'</span></div>'}
 function tools(){return '<div class="users-tools"><input id="usersSearch" type="search" placeholder="Pesquisar nome, email ou contacto…"><select id="usersFilter"><option value="">Todos os utilizadores</option><option value="complete">Perfil completo</option><option value="incomplete">Perfil incompleto</option><option value="admin">Administradores</option></select><button id="usersRefresh" type="button">Atualizar</button></div><div class="users-count" id="usersCount"></div>'}
 async function load(){panel.innerHTML=header()+tools()+'<div class="empty">A carregar utilizadores…</div>';var results=await Promise.all([sb.from('profiles').select('id,name,contact,avatar_path,created_at,updated_at').order('updated_at',{ascending:false}),sb.from('admin_users').select('user_id,role,created_at')]);var pr=results[0],ad=results[1];if(pr.error){panel.innerHTML=header()+tools()+'<div class="empty"><strong>Não foi possível carregar os utilizadores.</strong>'+esc(pr.error.message)+'</div>';bindTools();return}profiles=pr.data||[];admins=ad.data||[];render();bindTools()}
 function bindTools(){var s=document.getElementById('usersSearch'),f=document.getElementById('usersFilter'),r=document.getElementById('usersRefresh');if(s)s.oninput=render;if(f)f.onchange=render;if(r)r.onclick=load}
 function isAdmin(id){return admins.find(function(a){return a.user_id===id})||null}
 function complete(p){return !!(p.name&&p.name.trim()&&p.contact&&p.contact.trim())}
 function render(){var s=(document.getElementById('usersSearch')?.value||'').toLowerCase().trim(),f=document.getElementById('usersFilter')?.value||'',list=profiles.filter(function(p){var a=isAdmin(p.id),text=[p.name,p.contact,p.id].join(' ').toLowerCase();return (!s||text.indexOf(s)!==-1)&&(!f||(f==='admin'&&a)||(f==='complete'&&complete(p))||(f==='incomplete'&&!complete(p)))});var count=document.getElementById('usersCount');if(count)count.textContent=list.length+' utilizador'+(list.length===1?'':'es')+' visível'+(list.length===1?'':'is');panel.querySelectorAll('.user-card,.users-empty').forEach(function(x){x.remove()});if(!list.length){var e=document.createElement('div');e.className='empty users-empty';e.innerHTML='<strong>Nenhum utilizador encontrado</strong>Ajusta a pesquisa ou o filtro.';panel.appendChild(e);return}list.forEach(function(p){var a=isAdmin(p.id),card=document.createElement('article');card.className='admin-card user-card';card.dataset.userId=p.id;card.innerHTML='<div class="user-main">'+avatar(p.avatar_path,p.name,'')+'<div class="user-info"><span class="admin-meta">'+(a?'ADMINISTRADOR · '+esc(a.role):'UTILIZADOR')+'</span><h2>'+esc(p.name||'Sem nome')+'</h2><p>'+esc(p.contact||'Sem contacto')+'</p><small>ID: '+esc(p.id)+'</small></div></div><div class="admin-actions"><button type="button" data-edit-user="'+esc(p.id)+'" class="approve">Editar</button><button type="button" data-message-user="'+esc(p.id)+'">Enviar mensagem</button><button type="button" data-view-user="'+esc(p.id)+'">Ver perfil</button></div>';card.querySelector('[data-edit-user]').onclick=function(){editUser(card,p)};card.querySelector('[data-message-user]').onclick=function(){messageUser(p)};card.querySelector('[data-view-user]').onclick=function(){toggleDetails(card,p,a)};panel.appendChild(card)})}
 function editUser(card,p){var old=card.querySelector('.user-edit');if(old){old.remove();return}var form=document.createElement('form');form.className='user-edit';form.innerHTML='<input name="name" required maxlength="120" placeholder="Nome"><input name="contact" maxlength="120" placeholder="Contacto"><div><button type="submit" class="approve">Guardar alterações</button><button type="button" data-cancel>Cancelar</button></div><p class="status"></p>';form.name.value=p.name||'';form.contact.value=p.contact||'';card.appendChild(form);form.querySelector('[data-cancel]').onclick=function(){form.remove()};form.onsubmit=async function(e){e.preventDefault();var payload={name:form.name.value.trim(),contact:form.contact.value.trim(),updated_at:new Date().toISOString()},r=await sb.from('profiles').update(payload).eq('id',p.id);if(r.error){form.querySelector('.status').textContent='Erro: '+r.error.message;return}p.name=payload.name;p.contact=payload.contact;form.remove();render();bindTools()}}
 function messageUser(p){var contact=String(p.contact||'').trim();if(!contact){alert('Este utilizador não tem contacto guardado.');return}var text=prompt('Mensagem para '+(p.name||'utilizador')+':','Olá! Aqui é a Nzinga Creatives.');if(text===null)return;if(!text.trim())return;var digits=contact.replace(/[^0-9]/g,'');if(digits.length>=8){window.open('https://wa.me/'+digits+'?text='+encodeURIComponent(text),'_blank','noopener');return}window.location.href='mailto:?subject='+encodeURIComponent('Nzinga Creatives')+'&body='+encodeURIComponent(text)}
 function toggleDetails(card,p,a){var old=card.querySelector('.user-details');if(old){old.remove();return}var d=document.createElement('div');d.className='user-details';d.innerHTML='<div class="user-detail-top">'+avatar(p.avatar_path,p.name,'')+'<div><strong>'+esc(p.name||'Sem nome')+'</strong><div>'+esc(p.contact||'Sem contacto')+'</div></div></div><dl><dt>Função</dt><dd>'+(a?'Administrador ('+esc(a.role)+')':'Utilizador')+'</dd><dt>Conta</dt><dd>'+esc(date(p.created_at))+'</dd><dt>Perfil atualizado</dt><dd>'+esc(date(p.updated_at))+'</dd><dt>ID</dt><dd>'+esc(p.id)+'</dd></dl><div class="user-activity"><button type="button" data-orders-user>Ver pedidos</button><button type="button" data-reviews-user>Ver avaliações</button></div><div class="user-related" hidden></div>';card.appendChild(d);d.querySelector('[data-orders-user]').onclick=function(){loadRelated(d,p.id,'orders')};d.querySelector('[data-reviews-user]').onclick=function(){loadRelated(d,p.id,'reviews')}}
 async function loadRelated(details,id,type){var box=details.querySelector('.user-related');box.hidden=false;box.textContent='A carregar…';var table=type==='orders'?'orders':'reviews',r=await sb.from(table).select('*').eq('user_id',id).order('created_at',{ascending:false});if(r.error){box.textContent='Não foi possível carregar: '+r.error.message;return}var rows=r.data||[];box.innerHTML=rows.length?'<strong>'+esc(type==='orders'?'Pedidos':'Avaliações')+'</strong>'+rows.map(function(x){return '<div class="related-row"><b>'+esc(type==='orders'?(x.product_name||x.service||'Pedido'):(x.stars||'0')+' ★')+'</b> · '+esc(x.status||'')+'<br><span>'+esc(date(x.created_at))+'</span></div>'}).join(''):'Nenhum registo associado.'}
 function addStyle(){if(document.getElementById('nzinga-users-style'))return;var s=document.createElement('style');s.id='nzinga-users-style';s.textContent='.users-tools{padding:14px 20px;border-bottom:1px solid var(--admin-line);display:grid;grid-template-columns:minmax(180px,1fr) 190px auto;gap:8px;background:var(--admin-soft)}.users-tools input,.users-tools select{width:100%;box-sizing:border-box;padding:10px 11px;border:1px solid var(--admin-line);border-radius:10px;background:var(--admin-paper,#fff);color:inherit;font:inherit}.users-tools button,.user-activity button,.user-edit button{border:1px solid var(--admin-line);border-radius:10px;background:#fff;color:#050505;font-weight:800;padding:10px 14px;cursor:pointer}.users-count{font-size:.76rem;opacity:.55;padding:0 20px 12px}.user-main{display:flex;align-items:center;gap:14px}.user-avatar{width:52px;height:52px;border-radius:16px;object-fit:cover;border:1px solid var(--admin-line);flex:0 0 auto}.user-avatar-fallback{display:grid;place-items:center;background:var(--admin-soft);font-weight:900}.user-info{min-width:0}.user-info h2{margin:4px 0}.user-info p{margin:4px 0}.user-info small{opacity:.4;word-break:break-all}.user-details,.user-edit{margin-top:14px;padding:15px;border:1px solid var(--admin-line);border-radius:14px;background:var(--admin-soft);display:grid;gap:12px}.user-edit{grid-template-columns:1fr 1fr}.user-edit div,.user-edit .status{grid-column:1/-1}.user-edit input{padding:10px;border:1px solid var(--admin-line);border-radius:9px;background:var(--admin-paper,#fff);color:inherit}.user-details dl{margin:0;display:grid;grid-template-columns:150px 1fr;gap:7px 12px;font-size:.84rem}.user-details dt{opacity:.5}.user-details dd{margin:0;word-break:break-word}.user-activity{display:flex;gap:8px;flex-wrap:wrap}.user-activity button{background:transparent;color:inherit;font-weight:500}.user-related{padding:10px;border-radius:10px;background:rgba(0,0,0,.08);font-size:.82rem}.related-row{padding:8px 0;border-bottom:1px solid var(--admin-line)}.related-row:last-child{border-bottom:0}.related-row span{opacity:.5}@media(max-width:650px){.users-tools{grid-template-columns:1fr}.user-details dl{grid-template-columns:1fr}.user-edit{grid-template-columns:1fr}.user-edit div,.user-edit .status{grid-column:auto}.user-avatar{width:46px;height:46px}}';document.head.appendChild(s)}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();