(()=>{'use strict';
function ready(fn){document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn,{once:true}):fn()}
ready(()=>{
 const form=document.getElementById('authForm'),email=document.getElementById('authEmail'),password=document.getElementById('authPassword'),signup=document.getElementById('signupBtn'),authStatus=document.getElementById('authStatus');
 const cfg=window.NZINGA_SUPABASE;
 if(!window.supabase||!cfg?.url||!cfg?.publishableKey)return;
 const client=()=>window.supabase.createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
 if(form&&email&&password&&signup&&authStatus){
  const show=(m,b=false)=>{authStatus.textContent=m;authStatus.style.color=b?'#ffb3b3':'#fff'};
  form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();try{show('A entrar…');const {data,error}=await client().auth.signInWithPassword({email:email.value.trim(),password:password.value});if(error)throw error;if(!data.session)throw new Error('Não foi possível iniciar a sessão.');show('Sessão iniciada.');setTimeout(()=>location.reload(),300)}catch(e){show(e?.message||'Não foi possível iniciar sessão.',true)}},{capture:true});
  signup.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();try{const em=email.value.trim(),pw=password.value;if(!em||!pw){show('Preenche o e-mail e a palavra-passe.',true);return}if(pw.length<6){show('A palavra-passe deve ter pelo menos 6 caracteres.',true);return}show('A criar conta…');const {data,error}=await client().auth.signUp({email:em,password:pw,options:{emailRedirectTo:location.origin+'/minha-nzinga.html'}});if(error)throw error;if(data.session){show('Conta criada e sessão iniciada.');setTimeout(()=>location.reload(),300)}else show('Conta criada. Verifica o teu e-mail para confirmar e depois inicia sessão.')}catch(e){show(e?.message||'Não foi possível criar a conta.',true)}},{capture:true});
 }
 const pf=document.getElementById('profileForm'),nameEl=document.getElementById('profileName'),contactEl=document.getElementById('profileContact'),statusEl=document.getElementById('profileStatus'),titleEl=document.getElementById('profileTitle'),emailEl=document.getElementById('profileEmail'),input=document.getElementById('avatarInput'),img=document.getElementById('avatarImage'),initials=document.getElementById('avatarInitials'),remove=document.getElementById('removeAvatar');
 if(!pf||!nameEl||!contactEl)return;
 const sb=client();let user=null;
 const setStatus=(m,b=false)=>{if(statusEl){statusEl.textContent=m;statusEl.style.color=b?'#b00020':''}};
 const init=v=>(String(v||'N').trim().split(/\s+/).map(x=>x[0]).join('').slice(0,2)||'N').toUpperCase();
 const avatar=(url,name)=>{initials.textContent=init(name);if(url){img.src=url+'?v='+Date.now();img.classList.remove('hidden');initials.classList.add('hidden')}else{img.removeAttribute('src');img.classList.add('hidden');initials.classList.remove('hidden')}};
 const getUser=async()=>{const r=await sb.auth.getUser();return r?.data?.user||null};
 const load=async()=>{user=await getUser();if(!user)return;const r=await sb.from('profiles').select('name,contact,avatar_path').eq('id',user.id).maybeSingle();if(r.error){setStatus('Erro ao carregar perfil: '+r.error.message,true);return}const p=r.data||{};nameEl.value=p.name||'';contactEl.value=p.contact||'';emailEl.textContent=user.email||'';titleEl.textContent='Olá, '+(p.name||user.email?.split('@')[0]||'Nzinga')+'.';const url=p.avatar_path?sb.storage.from('profile-photos').getPublicUrl(p.avatar_path).data.publicUrl:null;avatar(url,p.name||user.email)};
 pf.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();if(!user)user=await getUser();if(!user){setStatus('A sessão expirou. Entra novamente.',true);return}const name=nameEl.value.trim(),contact=contactEl.value.trim();setStatus('A guardar…');const r=await sb.from('profiles').upsert({id:user.id,name,contact,updated_at:new Date().toISOString()},{onConflict:'id'});if(r.error){setStatus('Erro ao guardar: '+r.error.message,true);return}titleEl.textContent='Olá, '+(name||user.email?.split('@')[0]||'Nzinga')+'.';setStatus('Perfil guardado com sucesso.')},{capture:true});
 input?.addEventListener('change',async e=>{e.preventDefault();e.stopImmediatePropagation();if(!user)user=await getUser();const file=input.files?.[0];if(!user||!file)return;if(!file.type.startsWith('image/')){setStatus('Escolhe uma imagem válida.',true);return}if(file.size>6*1024*1024){setStatus('A foto deve ter no máximo 6 MB.',true);return}setStatus('A enviar foto…');const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'')||'jpg',path=user.id+'/'+Date.now()+'.'+ext;const up=await sb.storage.from('profile-photos').upload(path,file,{contentType:file.type,cacheControl:'3600',upsert:false});if(up.error){setStatus('Erro ao enviar foto: '+up.error.message,true);return}const old=await sb.from('profiles').select('avatar_path').eq('id',user.id).maybeSingle();const pr=await sb.from('profiles').upsert({id:user.id,avatar_path:path,updated_at:new Date().toISOString()},{onConflict:'id'});if(pr.error){await sb.storage.from('profile-photos').remove([path]);setStatus('Erro ao guardar a foto: '+pr.error.message,true);return}if(old.data?.avatar_path)await sb.storage.from('profile-photos').remove([old.data.avatar_path]);avatar(sb.storage.from('profile-photos').getPublicUrl(path).data.publicUrl,nameEl.value);setStatus('Foto de perfil atualizada.');input.value=''},{capture:true});
 remove?.addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();if(!user)user=await getUser();if(!user)return;setStatus('A remover foto…');const r=await sb.from('profiles').select('avatar_path').eq('id',user.id).maybeSingle();if(r.error){setStatus('Erro ao localizar a foto: '+r.error.message,true);return}if(r.data?.avatar_path)await sb.storage.from('profile-photos').remove([r.data.avatar_path]);const pr=await sb.from('profiles').upsert({id:user.id,avatar_path:null,updated_at:new Date().toISOString()},{onConflict:'id'});if(pr.error){setStatus('Erro ao remover: '+pr.error.message,true);return}avatar(null,nameEl.value);setStatus('Foto removida.')},{capture:true});
 load();
});
})();