(()=>{'use strict';
const THEME='nzinga-site-theme',LANG='nzinga-language';
const theme=()=>localStorage.getItem(THEME)==='dark'?'dark':'light';
const lang=()=>localStorage.getItem(LANG)==='en'?'en':'pt';
function addMenu(){if(!/minha-nzinga\.html$/i.test(location.pathname))return;const nav=document.getElementById('navLinks');if(nav&&!nav.querySelector('[data-settings-link]')){const a=document.createElement('a');a.href='settings.html';a.dataset.settingsLink='1';a.textContent='⚙ Definições';nav.appendChild(a)}}
function apply(){const t=theme();document.documentElement.dataset.nzingaTheme=t;document.documentElement.style.colorScheme=t;const m=document.querySelector('meta[name="theme-color"]');if(m)m.content=t==='dark'?'#101010':'#f4f1eb'}
function applyNavLanguage(){const en=lang()==='en';const header={Início:en?'Home':'Início',Serviços:en?'Services':'Serviços',NzingaGPT:'NzingaGPT',Surpresas:en?'Surprises':'Surpresas',Market:'Market',Raízes:en?'Roots':'Raízes','Minha Nzinga':en?'My Nzinga':'Minha Nzinga','⚙ Definições':en?'⚙ Settings':'⚙ Definições'};document.querySelectorAll('#navLinks a').forEach(a=>{const raw=a.textContent.trim();if(header[raw])a.textContent=header[raw]});document.querySelectorAll('.bottom-nav a small').forEach(s=>{const map={Início:en?'Home':'Início',Serviços:en?'Services':'Serviços',NzingaGPT:'NzingaGPT',Market:'Market','Minha Nzinga':en?'My Nzinga':'Minha Nzinga'};if(map[s.textContent])s.textContent=map[s.textContent]})}
function build(){if(!/settings\.html$/i.test(location.pathname))return;const root=document.getElementById('settingsRoot');if(!root)return;root.innerHTML='<div class="settings-head"><a class="button settings-back" href="minha-nzinga.html">← <span data-i18n="back">Voltar à Minha Nzinga</span></a><p class="eyebrow">MINHA NZINGA · <span data-i18n="settings">DEFINIÇÕES</span></p><h1><span data-i18n="settingsTitle">Definições.</span></h1><p data-i18n="intro">Algumas opções essenciais para personalizar a tua experiência na Nzinga Creatives.</p></div><section class="settings-card"><h2 data-i18n="appearance">Aparência</h2><p data-i18n="appearanceDesc">Escolhe o visual que preferes. A escolha fica guardada neste dispositivo.</p><div class="settings-options"><button class="settings-option" data-theme="light">☀ Claro<small data-i18n="lightDesc">Visual claro e limpo.</small></button><button class="settings-option" data-theme="dark">☾ Escuro<small data-i18n="darkDesc">Visual escuro para ambientes com pouca luz.</small></button></div></section><section class="settings-card"><h2 data-i18n="language">Idioma</h2><p data-i18n="languageDesc">Escolhe o idioma da interface. Por enquanto, estão disponíveis Português e English.</p><div class="settings-options"><button class="settings-option" data-lang="pt">🇦🇴 Português<small>Português (Angola)</small></button><button class="settings-option" data-lang="en">🇬🇧 English<small>English</small></button></div></section><section class="settings-card"><h2 data-i18n="preferences">Preferências</h2><p data-i18n="preferencesDesc">Mais opções simples podem ser adicionadas aqui no futuro, sem deixar as definições complicadas.</p></section>';
const T={pt:{back:'Voltar à Minha Nzinga',settings:'DEFINIÇÕES',settingsTitle:'Definições.',intro:'Algumas opções essenciais para personalizar a tua experiência na Nzinga Creatives.',appearance:'Aparência',appearanceDesc:'Escolhe o visual que preferes. A escolha fica guardada neste dispositivo.',lightDesc:'Visual claro e limpo.',darkDesc:'Visual escuro para ambientes com pouca luz.',language:'Idioma',languageDesc:'Escolhe o idioma da interface. Por enquanto, estão disponíveis Português e English.',preferences:'Preferências',preferencesDesc:'Mais opções simples podem ser adicionadas aqui no futuro, sem deixar as definições complicadas.'},en:{back:'Back to My Nzinga',settings:'SETTINGS',settingsTitle:'Settings.',intro:'A few essential options to personalize your Nzinga Creatives experience.',appearance:'Appearance',appearanceDesc:'Choose the look you prefer. Your choice is saved on this device.',lightDesc:'Light and clean view.',darkDesc:'Dark view for low-light environments.',language:'Language',languageDesc:'Choose the interface language. Portuguese and English are currently available.',preferences:'Preferences',preferencesDesc:'More simple options can be added here in the future without making settings complicated.'}};
function refresh(){const l=lang();document.documentElement.lang=l==='en'?'en':'pt-AO';root.querySelectorAll('[data-i18n]').forEach(e=>{e.textContent=T[l][e.dataset.i18n]||e.textContent});root.querySelectorAll('[data-theme]').forEach(b=>{const on=b.dataset.theme===theme();b.classList.toggle('active',on);b.setAttribute('aria-pressed',on?'true':'false')});root.querySelectorAll('[data-lang]').forEach(b=>{const on=b.dataset.lang===l;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on?'true':'false')});applyNavLanguage()}root.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{localStorage.setItem(THEME,b.dataset.theme);apply();refresh()});root.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{localStorage.setItem(LANG,b.dataset.lang);refresh()});refresh()}
function boot(){addMenu();apply();build();applyNavLanguage()}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();})();