(()=>{'use strict';
const LANG='nzinga-language',COOKIE='nzinga_cookie_consent',MOTION='nzinga-reduced-motion';
const lang=()=>localStorage.getItem(LANG)==='en'?'en':'pt';
const reduced=()=>localStorage.getItem(MOTION)==='1';
const cookie=()=>{const m=document.cookie.match(/(?:^|; )nzinga_cookie_consent=([^;]+)/);return m?decodeURIComponent(m[1]):''};
const T={pt:{back:'Voltar à Minha Nzinga',title:'Definições.',intro:'Controla as opções essenciais da tua experiência na Nzinga Creatives.',language:'Idioma',languageDesc:'Neste momento, a Nzinga está disponível em Português e English.',country:'País e moeda',countryDesc:'A região e a moeda são definidas pelo painel de administração.',locked:'Definido automaticamente',cookies:'Cookies',cookiesDesc:'Controla o consentimento para guardar preferências.',allow:'✓ Permitir preferências',allowDesc:'Permitir guardar preferências do site.',essential:'✓ Apenas essenciais',essentialDesc:'Manter apenas o necessário.',saved:'Preferência de cookies guardada.',preferences:'Preferências',preferencesDesc:'Opções de conforto e acessibilidade.',motion:'Animações',motionOn:'✓ Animações normais',motionOnDesc:'Mantém transições e movimentos.',motionOff:'✓ Reduzir animações',motionOffDesc:'Reduz movimentos para uma experiência mais confortável.',reset:'Repor preferências',resetDesc:'Volta às opções padrão.',resetDone:'Preferências repostas.'},en:{back:'Back to My Nzinga',title:'Settings.',intro:'Control the essential options for your Nzinga Creatives experience.',language:'Language',languageDesc:'Nzinga currently supports Portuguese and English.',country:'Country & currency',countryDesc:'The region and currency are controlled from the administrator panel.',locked:'Set automatically',cookies:'Cookies',cookiesDesc:'Control consent for saved preferences.',allow:'✓ Allow preferences',allowDesc:'Allow saving site preferences.',essential:'✓ Essential only',essentialDesc:'Keep only what is required.',saved:'Cookie preference saved.',preferences:'Preferences',preferencesDesc:'Comfort and accessibility options.',motion:'Animations',motionOn:'✓ Normal animations',motionOnDesc:'Keep interface transitions and movement.',motionOff:'✓ Reduce animations',motionOffDesc:'Reduce movement for a more comfortable experience.',reset:'Reset preferences',resetDesc:'Return to default options.',resetDone:'Preferences reset.'}};
function apply(){document.documentElement.dataset.nzingaTheme='dark';document.documentElement.style.colorScheme='dark';document.documentElement.classList.toggle('nzinga-reduced-motion',reduced());const m=document.querySelector('meta[name="theme-color"]');if(m)m.content='#111111'}
function setCookie(v){document.cookie=COOKIE+'='+encodeURIComponent(v)+'; path=/; max-age=31536000; SameSite=Lax'}
function build(){const root=document.getElementById('settingsRoot');if(!root)return;root.innerHTML='<div class="settings-head"><a class="button settings-back" href="minha-nzinga.html">← <span data-i="back"></span></a><p class="eyebrow">MINHA NZINGA · DEFINIÇÕES</p><h1 data-i="title"></h1><p data-i="intro"></p></div><section class="settings-card"><h2 data-i="language"></h2><p data-i="languageDesc"></p><div class="settings-options"><button class="settings-option" data-lang="pt">Português<small>Português</small></button><button class="settings-option" data-lang="en">English<small>English</small></button></div></section><section class="settings-card"><h2 data-i="country"></h2><p data-i="countryDesc"></p><div class="settings-option nz-country-locked"><span id="settingsCountryValue">Angola · Kwanza (AOA)</span><small data-i="locked"></small></div></section><section class="settings-card"><h2 data-i="cookies"></h2><p data-i="cookiesDesc"></p><div class="settings-options"><button class="settings-option" data-cookie="all"><span data-i="allow"></span><small data-i="allowDesc"></small></button><button class="settings-option" data-cookie="essential"><span data-i="essential"></span><small data-i="essentialDesc"></small></button></div><p class="settings-status" id="cookieStatus"></p></section><section class="settings-card"><h2 data-i="preferences"></h2><p data-i="preferencesDesc"></p><h3 data-i="motion"></h3><div class="settings-options"><button class="settings-option" data-motion="normal"><span data-i="motionOn"></span><small data-i="motionOnDesc"></small></button><button class="settings-option" data-motion="reduced"><span data-i="motionOff"></span><small data-i="motionOffDesc"></small></button></div><div class="settings-options settings-reset"><button class="settings-option" data-reset="1"><span data-i="reset"></span><small data-i="resetDesc"></small></button></div><p class="settings-status" id="preferencesStatus"></p></section>'};
function refresh(){const l=lang(),t=T[l],root=document.getElementById('settingsRoot'),country=(window.NZINGA_GET_COUNTRY&&window.NZINGA_GET_COUNTRY())||null;if(!root)return;document.documentElement.lang=l==='pt'?'pt-AO':'en';root.querySelectorAll('[data-i]').forEach(e=>e.textContent=t[e.dataset.i]||'');root.querySelectorAll('[data-lang]').forEach(b=>{const on=b.dataset.lang===l;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});root.querySelectorAll('[data-cookie]').forEach(b=>{const v=cookie();const on=b.dataset.cookie===v||(!v&&b.dataset.cookie==='essential');b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});root.querySelectorAll('[data-motion]').forEach(b=>{const on=(b.dataset.motion==='reduced')===reduced();b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});const cv=root.querySelector('#settingsCountryValue');if(cv&&country)cv.textContent=country.flag+' '+country.name+' · '+country.currency}
function wire(){const root=document.getElementById('settingsRoot');if(!root)return;root.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{localStorage.setItem(LANG,b.dataset.lang);refresh()});root.querySelectorAll('[data-cookie]').forEach(b=>b.onclick=()=>{setCookie(b.dataset.cookie);const s=document.getElementById('cookieStatus');if(s)s.textContent=T[lang()].saved;refresh()});root.querySelectorAll('[data-motion]').forEach(b=>b.onclick=()=>{localStorage.setItem(MOTION,b.dataset.motion==='reduced'?'1':'0');apply();refresh()});const reset=root.querySelector('[data-reset]');if(reset)reset.onclick=()=>{localStorage.removeItem(LANG);localStorage.removeItem(MOTION);apply();refresh();const s=document.getElementById('preferencesStatus');if(s)s.textContent=T[lang()].resetDone};refresh()}
function boot(){apply();build();wire()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot()
})();