/* Nzinga Creatives — tradução global PT/EN
   A conversão monetária é delegada ao price-display-fix.js para manter um preço-base estável. */
(function(){'use strict';
const LANG_KEY='nzinga-language';
const DICT={en:{
'Início':'Home','Serviços':'Services','Surpresas':'Surprises','Raízes':'Roots','Começar':'Start','Começar agora':'Start now','Explorar':'Explore','Explorar ↓':'Explore ↓','Definições':'Settings','Market':'Market','O que queres':'What do you want to','criar?':'create?','Design, conteúdo, documentos, experiências digitais e produtos criativos — num só espaço.':'Design, content, documents, digital experiences and creative products — all in one place.','Começa pela tua ideia.':'Start with your idea.','Escolhe o que precisas agora. A Nzinga cresce contigo.':'Choose what you need now. Nzinga grows with you.','Quero criar uma marca':'I want to create a brand','Quero criar conteúdo':'I want to create content','Quero criar algo digital':'I want to create something digital','Quero algo pronto':'I want something ready-made','Ver serviços →':'View services →','Explorar →':'Explore →','Ir para o Market →':'Go to Market →','Mais do que serviços.':'More than services.','Como funciona':'How it works','Simples por fora. Estruturado por dentro.':'Simple on the outside. Structured inside.','Escolhe':'Choose','Personaliza':'Customize','Acompanha':'Track','Uma ideia começa pequena.':'An idea starts small.','Vamos dar-lhe forma.':'Let’s give it shape.','Abrir NzingaGPT →':'Open NzingaGPT →','Ideias que ganham forma.':'Ideas taking shape.','Feito em Angola.':'Made in Angola.','Escolhe o que':'Choose what you','queres':'want to','Pesquisar um serviço…':'Search a service…','Do pedido à criação.':'From request to creation.','Explica':'Explain','Pedido':'Request','Pagamento':'Payment','Continuar para checkout →':'Continue to checkout →','Nome':'Name','Contacto':'Contact','Nível':'Level','O que queres criar?':'What do you want to create?','Ainda não há nada nesta prateleira. Mas pode aparecer.':'There is nothing on this shelf yet. But it may appear.','Tudo':'All','Templates':'Templates','Documentos':'Documents','Ebooks':'Ebooks','Artes':'Art','Em breve':'Coming soon','Quero participar →':'I want to participate →','Novo pedido':'New request','Começar projeto':'Start project','A verificar acesso administrativo…':'Checking administrative access…','Acesso restrito':'Access restricted','Sair da conta':'Sign out','Visão geral':'Overview','Resumo e gestão das áreas administrativas.':'Summary and management of administrative areas.','Pedidos':'Orders','Avaliações':'Reviews','Utilizadores':'Users','Equipa':'Team','Atividades':'Activity','País':'Country','Moeda':'Currency','Idioma':'Language','Pré-visualização regional':'Regional preview','Ver site como este país':'View site as this country','Guardar região':'Save region','Região do administrador':'Administrator region','Esta escolha serve para testar a experiência de outros mercados.':'This choice is for testing the experience of other markets.','Preço de referência':'Reference price'
}};
function lang(){return localStorage.getItem(LANG_KEY)==='en'?'en':'pt'}
function translate(root){const l=lang();document.documentElement.lang=l==='pt'?'pt-AO':'en';const d=DICT[l];if(!d)return;const w=document.createTreeWalker(root||document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(w.nextNode())nodes.push(w.currentNode);nodes.forEach(n=>{const raw=n.nodeValue.trim();if(raw&&d[raw])n.nodeValue=n.nodeValue.replace(raw,d[raw])});document.querySelectorAll('input[placeholder],textarea[placeholder],input[aria-label],button[aria-label]').forEach(el=>{const attr=el.placeholder?'placeholder':'aria-label',v=el.getAttribute(attr);if(v&&d[v])el.setAttribute(attr,d[v])});}
function money(){if(window.NZINGA_PRICE?.refresh)window.NZINGA_PRICE.refresh()}
function boot(){translate(document.body);money();let last=lang();setInterval(()=>{const now=lang();if(now!==last){last=now;location.reload()}},700);new MutationObserver(()=>{translate(document.body);money()}).observe(document.body,{childList:true,subtree:true})}
window.NZINGA_I18N={translate,money};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();